### ISSUE TITLE
Download full history returns invalid results

### ISSUE THREAD

**Issue by kbhutani0001** [thealphadollar/messiah#61]
When clicked on download full history button, invalid result is returned. Insead of download option, csv is returned on page

![Uploading Screenshot from 2018-12-08 02-03-55.png…]()

**Comment by thealphadollar** [comment]
Yes, and I think it is meant to be that way. What do you propose?

**Comment by swghosh** [comment]
It's in the form of a JSON indeed. If you're looking for improvements maybe it can be converted into CSV format and if the appropriate mime type is put for CSV, browser should directly download it instead of displaying the contents. CSV files would be more readable that JSON files (in my opinion) for someone non-technical. I guess that this helps.

**Comment by kbhutani0001** [comment]
It's not an api then why return it in a json format?
This page is for normal non tech people and I don't think anyone of them would even get what's written their

**Comment by thealphadollar** [comment]
Okay, sounds good.

**Comment by theartist007** [comment]
#70
